### ISSUE TITLE
Markbot issue - Screenshot Comparison

### ISSUE THREAD

**Issue by emahadzimustafic** [emahadzimustafic/dinosaur-designs#1]
Markbot says that my website is too visually different from the website screenshot (32% difference, expects less than 13%).
How do I fix this?

@hellachella @carolsinc

**Comment by carolsinc** [comment]
If you look at the text under the second and third images they are taking up way too much space. They should be figcaptions, not paragraphs. This is why you put a class on the first one to differentiate it from the other two.

**Comment by emahadzimustafic** [comment]
I fixed that, thanks! I still seem to have a screenshot error of 14% difference, and I've triple-checked my code and I can't seem to find the error (probably because coding is new to me). Is it something to do with the header or list? I see a slight space difference.
@hellachella @carolsinc

**Comment by hellachella** [comment]
This code is perfect and fully passes on my end. Are you using a PC or a mac? Somtimes it makes a difference.

**Comment by hellachella** [comment]
I have graded it manually.

**Comment by emahadzimustafic** [comment]
I use a PC. Thanks! I appreciate it
